application: perseqer
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


- url: /css
  static_dir: bootstrap/css
- url: /js
  static_dir: bootstrap/js
- url: /img
  static_dir: bootstrap/img

- url: .*
  script: main.py

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: webapp2
  version: "2.3"
